[package]
name = "hello-rust"
version = "0.2.1"
edition = "2021"
description = "Rustacean hopeful"
repository = "https://github.com/pythoninthegrass/hello-rust"
license = "MIT OR Apache-2.0"

[dependencies]
dotenvy = { version = "0.15.7", features = ["cli"] }
